import { TEXT } from './language.js';
const $ = (selector) => document.querySelector(selector);
export const elements = {
  canvas: $('#drawingCanvas'),
  baseCanvas: $('#baseCanvas'),
  stage: $('#canvasStage'),
  canvasWrapper: $('#canvasWrapper'),
  fullscreenPalette: $('#fullscreenPalette'),
  ctx: $('#drawingCanvas')?.getContext('2d') ?? null,
  baseCtx: $('#baseCanvas')?.getContext('2d') ?? null,
  importBaseBtn: $('#importBaseBtn'),
  clearBaseBtn: $('#clearBaseBtn'),
  toggleFullscreenBtn: $('#toggleFullscreenBtn'),
  toggleReferenceBtn: $('#toggleReferenceBtn'),
  exportBtn: $('#exportBtn'),
  importProjectBtn: $('#importProjectBtn'),
  createCanvasBtn: $('#createCanvasBtn'),
  toolPencilBtn: $('#toolPencilBtn'),
  toolBucketBtn: $('#toolBucketBtn'),
  toolEyedropperBtn: $('#toolEyedropperBtn'),
  toolSelectionBtn: $('#toolSelectionBtn'),
  flipHorizontalBtn: $('#flipHorizontalBtn'),
  flipVerticalBtn: $('#flipVerticalBtn'),
  rotateClockwiseBtn: $('#rotateClockwiseBtn'),
  rotateCounterclockwiseBtn: $('#rotateCounterclockwiseBtn'),
  baseImageInput: $('#baseImageInput'),
  widthInput: $('#widthInput'),
  heightInput: $('#heightInput'),
  resolutionInput: $('#resolutionInput'),
  zoomRange: $('#zoomRange'),
  autoSnapToggle: $('#autoSnapToggle'),
  showCodesToggle: $('#showCodesToggle'),
  canvasOpacityRange: $('#canvasOpacityRange'),
  baseLayerSelect: $('#baseLayerSelect'),
  baseScaleRange: $('#baseScaleRange'),
  baseScaleInput: $('#baseScaleInput'),
  resizeCanvasBtn: $('#resizeCanvasBtn'),
  resizeCanvasOverlay: $('#resizeCanvasOverlay'),
  resizeCloseBtn: $('#resizeCloseBtn'),
  resizeModeExpandBtn: $('#resizeModeExpandBtn'),
  resizeModeCropBtn: $('#resizeModeCropBtn'),
  resizeEditButtons: document.querySelectorAll('.resize-edit-btn'),
  resizeEditValues: document.querySelectorAll('.resize-edit-value'),
  resizePreviewStage: $('#resizePreviewStage'),
  resizePreviewWrapper: $('#resizePreviewWrapper'),
  resizePreviewDrawingCanvas: $('#resizePreviewDrawingCanvas'),
  resizeCurrentSize: $('#resizeCurrentSize'),
  resizeResultSize: $('#resizeResultSize'),
  resizeMessage: $('#resizeMessage'),
  resizeConfirmBtn: $('#resizeConfirmBtn'),
  resizeCancelBtn: $('#resizeCancelBtn'),
  toggleBaseEditBtn: $('#toggleBaseEditBtn'),
  recenterBaseBtn: $('#recenterBaseBtn'),
  snapBaseToCanvasBtn: $('#snapBaseToCanvasBtn'),
  paletteContainer: $('#paletteContainer'),
  paletteFilter: $('#paletteFilter'),
  paletteHistorySelect: $('#paletteHistorySelect'),
  loadDefaultPaletteBtn: $('#loadDefaultPaletteBtn'),
  importPaletteBtn: $('#importPaletteBtn'),
  deletePaletteBtn: $('#deletePaletteBtn'),
  paletteFileInput: $('#paletteFileInput'),
  canvasHighlightBtn: $('#canvasHighlightBtn'),
  projectFileInput: $('#projectFileInput'),
  currentColorInfo: $('#currentColorInfo'),
  statusSize: $('#statusSize'),
  statusBase: $('#statusBase'),
  statusPalette: $('#statusPalette'),
  canvasOpacityValue: $('#canvasOpacityValue'),
  baseScaleValue: $('#baseScaleValue'),
  referenceWindow: $('#referenceWindow'),
  docsWindow: $('#docsWindow'),
  updateWindow: $('#updateWindow'),
  exportWindow: $('#exportWindow'),
  referenceList: $('#referenceList'),
  referenceHeader: $('#referenceHeader'),
  referenceAddBtn: $('#referenceAddBtn'),
  referenceMinimizeBtn: $('#referenceMinimizeBtn'),
  referenceCloseBtn: $('#referenceCloseBtn'),
  referenceResizer: $('#referenceResizer'),
  referenceImageInput: $('#referenceImageInput'),
  docsCloseBtn: $('#docsCloseBtn'),
  docsToggleBtn: $('#docsToggleBtn'),
  updateCloseBtn: $('#updateCloseBtn'),
  updateManualBtn: $('#updateManualBtn'),
  exportCloseBtn: $('#exportCloseBtn'),
  exportCancelBtn: $('#exportCancelBtn'),
  exportConfirmBtn: $('#exportConfirmBtn'),
  exportPreviewCanvas: $('#exportPreviewCanvas'),
  exportBackgroundColor: $('#exportBackgroundColor'),
  exportFilename: $('#exportFilename'),
  colorManageBtn: $('#colorManageBtn'),
  colorManageWindow: $('#colorManageWindow'),
  colorManageCloseBtn: $('#colorManageCloseBtn'),
  colorManageCancelBtn: $('#colorManageCancelBtn'),
  colorManageConfirmBtn: $('#colorManageConfirmBtn'),
  selectAllColorsBtn: $('#selectAllColorsBtn'),
  deselectAllColorsBtn: $('#deselectAllColorsBtn'),
  colorManageList: $('#colorManageList'),
  colorManageMessage: $('#colorManageMessage'),
  enabledColorCount: $('#enabledColorCount'),
  canvasHighlightWindow: $('#canvasHighlightWindow'),
  canvasHighlightCloseBtn: $('#canvasHighlightCloseBtn'),
  canvasHighlightSelectAllBtn: $('#canvasHighlightSelectAll'),
  canvasHighlightDeselectAllBtn: $('#canvasHighlightDeselectAll'),
  canvasHighlightList: $('#canvasHighlightList'),
  canvasHighlightFilter: $('#canvasHighlightFilter'),
  canvasHighlightReplaceSelect: $('#canvasHighlightReplaceSelect'),
  canvasHighlightApplyReplaceBtn: $('#canvasHighlightApplyReplace'),
  canvasHighlightMessage: $('#canvasHighlightMessage'),
  paletteSwitchOverlay: $('#paletteSwitchOverlay'),
  paletteSwitchCloseBtn: $('#paletteSwitchCloseBtn'),
  paletteSwitchCancelBtn: $('#paletteSwitchCancelBtn'),
  paletteSwitchConvertBtn: $('#paletteSwitchConvertBtn'),
  paletteSwitchResetBtn: $('#paletteSwitchResetBtn'),
  paletteSwitchName: $('#paletteSwitchName'),
  canvasSizeWarning: $('#canvasSizeWarning'),
  selectionMaskCanvas: $('#selectionMaskCanvas'),
  selectionContentCanvas: $('#selectionContentCanvas'),
  selectionOutlineCanvas: $('#selectionOutlineCanvas'),
  selectionMaskCtx: $('#selectionMaskCanvas')?.getContext('2d') ?? null,
  selectionContentCtx: $('#selectionContentCanvas')?.getContext('2d') ?? null,
  selectionOutlineCtx: $('#selectionOutlineCanvas')?.getContext('2d') ?? null,
};
export const fullscreenBaseEditBtn = (() => {
  const btn = document.createElement('button');
  btn.id = 'fullscreenBaseEditBtn';
  btn.type = 'button';
  btn.textContent = TEXT.buttons.baseEdit;
  btn.style.display = 'none';
  document.body.appendChild(btn);
  return btn;
})();
