export const TEXT = {
  meta: {
    title: '拼豆像素画工具 - 免费在线拼豆草图制作',
    description: '拼豆像素画工具 - 由闷香红烧鱼制作的免费拼豆手工草图创作工具'
  },
  header: {
    title: '拼豆像素画工具',
    subtitle: '由"闷香红烧鱼"制作，详细使用可看右侧说明书'
  },
  app: {
    initFailed: '应用初始化失败:'
  },
  buttons: {
    updateManual: '更新',
    docs: '说明书',
    importBase: '导入底图',
    clearBase: '清除底图',
    export: '导出',
    importProject: '导入 .pd',
    fullscreen: '全屏绘制',
    referenceWindow: '参考图窗',
    createCanvas: '新建画布',
    resizeCanvas: '扩/裁画布',
    loadDefaultPalette: '加载内置 DMC',
    importPalette: '导入色卡 JSON',
    colorManage: '颜色管理',
    colorHighlight: '颜色高亮',
    deletePalette: '删除色卡',
    baseEdit: '底图编辑',
    baseRecenter: '底图居中',
    baseSnap: '贴合画布',
    selectAll: '全选',
    deselectAll: '全不选',
    exportAllHighlightImages: '导出所有颜色高亮图',
    cancel: '取消',
    confirm: '确认',
    confirmExport: '确认导出',
    exporting: '导出中...',
    applyReplace: '一键替换',
    convertPalette: '转换颜色',
    resetCanvas: '新建画布'
  },
  aria: {
    updateManual: '更新手册',
    openDocs: '打开说明书',
    docsButtonTitle: '说明书',
    canvasPane: '画布区域',
    toolbar: '绘图工具',
    controlPanel: '控制面板',
    referenceAdd: '添加参考图',
    referenceMinimize: '最小化参考窗',
    referenceRestore: '还原参考窗',
    referenceClose: '关闭参考窗',
    docsClose: '关闭说明书',
    updateClose: '关闭更新说明',
    exportClose: '关闭导出设置',
    resizeClose: '关闭画布尺寸调整窗口',
    colorManageClose: '关闭颜色管理',
    highlightClose: '关闭颜色高亮窗口',
    paletteSwitchClose: '关闭色卡切换提示',
    baseScaleInput: '底图缩放数值'
  },
  toolbar: {
    groupLabel: '绘图工具',
    tools: {
      pencil: '铅笔',
      bucket: '油漆桶',
      eyedropper: '吸管',
      selection: '矩形选区'
    },
    dropdown: {
      label: '图像操作',
      items: {
        flipHorizontal: '水平翻转',
        flipVertical: '垂直翻转',
        rotateClockwise: '顺时针旋转',
        rotateCounterclockwise: '逆时针旋转'
      }
    }
  },
  toggles: {
    autoSnap: '自动贴合底图颜色',
    showCodes: '显示色号',
    zoom: '缩放'
  },
  labels: {
    newCanvasSection: '新建画布',
    widthInput: '宽度 (像素)',
    heightInput: '高度 (像素)',
    resolutionInput: '像素比例（1 : N）',
    resolutionSuffix: '像素',
    canvasOpacity: '画布背景透明度',
    paletteSection: '色卡',
    paletteHistory: '已加载色卡',
    paletteFilter: '筛选色号/颜色',
    currentColorPrefix: '当前色号：',
    currentColorEmpty: '无',
    baseSection: '底图设置',
    baseLayer: '底图图层',
    baseLayerOptions: {
      under: '底图在画布下',
      over: '底图在画布上',
      hidden: '隐藏底图'
    },
    baseScale: '底图缩放',
    statusSection: '状态',
    statusCanvas: '画布：',
    statusBase: '底图：',
    statusPalette: '色卡：',
    exportPreviewTitle: '预览',
    exportPreviewHint: '(滚轮缩放 · 拖拽移动 · 双击重置)',
    exportFileSection: '文件设置',
    exportFilenameLabel: '文件名',
    exportOptionsSection: '导出选项',
    exportDisplaySection: '显示选项',
    exportBackgroundSection: '背景设置',
    highlightSection: '颜色高亮',
    resizeTitle: '编辑画布尺寸',
    resizeModeLabel: '调整模式',
    resizeEdit: '编辑',
    resizeCurrent: '当前尺寸：',
    resizeResult: '调整后：',
    resizeUnknownResult: '调整后：—',
    colorManageTitle: '颜色管理',
    paletteSwitchTitle: '切换色卡',
    paletteSwitchSummary: '切换色卡会影响当前画布的颜色，请选择处理方式。',
    paletteSwitchTarget: '目标色卡：',
    docsTitle: '说明书',
    updateTitle: '更新说明',
    exportTitle: '导出设置'
  },
  placeholders: {
    selectPalette: '请选择色卡',
    paletteFilter: '输入色号或关键字',
    highlightSearch: '搜索颜色代码...',
    highlightLoading: '正在加载颜色...',
    exportFilename: '输入文件名',
    colorManageLoading: '正在加载颜色...',
    highlightReplacePlaceholder: '请选择目标颜色'
  },
  status: {
    canvasNotCreated: '未创建',
    baseNotImported: '未导入',
    baseNotLoaded: '未加载',
    paletteNotLoaded: '未加载',
    colorCodeNone: '无',
    paletteUnnamed: '未命名'
  },
  base: {
    notLoaded: '未导入',
    exitEdit: '退出底图编辑',
    enterEdit: '编辑底图',
    anchors: {
      center: '居中',
      topLeft: '左上',
      topRight: '右上',
      bottomLeft: '左下',
      bottomRight: '右下'
    },
    locateLabel: (label) => `定位：${label}`,
    locateAria: (label) => `定位到${label}`,
    editingEnabled: '🎯 底图编辑模式已开启',
    editingDisabled: '❌ 底图编辑模式已关闭'
  },
  warnings: {
    canvas: {
      danger: (width, height) => `当前设置为 ${width} × ${height}，超大的画布可能导致严重卡顿。`,
      warning: (width, height) => `当前设置为 ${width} × ${height}，过大的画布可能导致卡顿。`
    }
  },
  alerts: {
    createCanvasFirst: '请先创建画布。',
    createCanvasBeforeExport: '请先创建画布后再导出。',
    loadPaletteFirst: '请先加载色卡',
    invalidPd: 'PD 文件内容无效或已损坏。',
    pdCanvasTooLarge: 'PD 文件中的画布尺寸超出限制。',
    pdImportComplete: 'PD 文件导入完成。',
    pdImportFailed: '无法导入 PD 文件，请确认文件格式正确。',
    pdPaletteEmpty: 'PD 文件中的色卡为空，无法导入。',
    imageLoadFailed: '图片加载失败，请检查图片格式'
  },
  confirm: {
    newCanvas: '新建画布会清空当前画布的颜色，是否继续？',
    importPdOverwrite: '导入 PD 文件会覆盖当前画布内容，是否继续？',
    resizeCropDeletion: '裁剪区域包含像素，继续操作将删除这些像素。是否确认？',
    removeReference: '确定删除这张参考图吗？',
    replaceBase: '当前已有底图，是否替换？'
  },
  prompts: {
    resizeAmount: (sideLabel, actionLabel) => `请输入需要在${sideLabel}侧${actionLabel}的像素数量 (可输入 0)：`
  },
  resize: {
    title: '编辑画布尺寸',
    closeAria: '关闭画布尺寸调整窗口',
    modeLabel: '调整模式',
    modeExpand: '扩图',
    modeCrop: '切图',
    editButton: '编辑',
    pixelSuffix: '像素',
    initialEditValue: (value) => `${value} 像素`,
    currentSizeLabel: '当前尺寸：',
    resultSizeLabel: '调整后：',
    resultUnknown: '调整后：—',
    messages: {
      noCanvas: '当前无画布可调整。',
      invalidValue: '调整值导致画布尺寸无效，请检查输入。',
      outOfRange: '调整后尺寸需在 1 - 2048 像素之间。',
      cropContainsPixels: '裁剪区域包含像素，确认后这些像素将被删除。',
      expandHint: '将在画布四周添加空白区域。',
      cropHint: '将从所选方向裁剪画布。'
    },
    sideLabels: {
      top: '上',
      right: '右',
      bottom: '下',
      left: '左'
    },
    expandAction: '增加',
    cropAction: '裁剪'
  },
  palette: {
    notSelected: '未选择色卡',
    defaultLabel: '默认色卡',
    customLabel: '自定义色卡',
    customLabelShort: '自定义',
    builtinSuffix: '（内置）',
    historyPlaceholder: '请选择色卡',
    optionLabel: (name, count) => `${name}(${count}色)`,
    statusLabel: (label, count) => `${label}· ${count}色`,
    notLoadedMessage: '尚未加载色卡',
    filterNoMatch: '未找到匹配的颜色。',
    enabledCount: (enabled, total) => `已启用: ${enabled}/${total}`,
    alerts: {
      emptyOrInvalid: '色卡为空或格式不正确。',
      parseFailed: '色卡文件解析失败，请确认格式正确为 JSON。',
      builtinNotRemovable: '内置色卡不能删除。',
      notFound: '未找到该色卡。',
      dmcNotReady: '内置 DMC 色卡尚未准备好，请先导入 JSON。'
    },
    confirmDelete: (name) => `确认删除色卡「${name}」吗？此操作不可撤销。`,
    messages: {
      noAvailableColors: '暂无可用颜色',
      needAtLeastOne: '至少需要启用一个颜色',
      preservedOne: '已保留至少一个颜色',
      lowEnabledWarning: '启用的颜色较少，可能会影响绘制',
      mustEnableOne: '必须至少启用一个颜色',
      updated: '颜色设置已更新'
    }
  },
  colorManagement: {
    loading: '正在加载颜色...',
    selectAll: '全选',
    deselectAll: '全不选'
  },
  highlight: {
    noMatch: '没有符合条件的颜色',
    colorCount: (count) => `${count} 个像素`,
    formatUnsupported: '当前高亮仅支持 PNG 或 JPG 格式',
    formatAutoSwitched: '已自动切换到可用的导出格式。',
    noExportableColors: '当前没有可导出的颜色。',
    zipMissing: '未找到 JSZip，无法打包导出。',
    defaultFilename: 'pixel-art',
    progressGenerating: '正在生成颜色高亮导出...',
    progressExportingColor: (code) => `正在导出颜色 ${code}...`,
    progressAllDone: '所有颜色均已导出',
    exportFinished: '颜色高亮导出完成，已下载压缩包。',
    exportErrorConsole: '导出颜色高亮失败',
    exportErrorMessage: (message) => `导出颜色高亮失败：${message}`,
    jpgBackgroundWarning: 'JPG 不支持透明背景，已自动使用纯色背景。',
    canvasTitle: '颜色高亮导出预览',
    canvasTotalLabel: (total) => `所选颜色像素总数：${total}`,
    canvasSectionTitle: '高亮颜色',
    canvasEmptyHint: '未选择任何颜色',
    canvasPaletteLabel: (palette) => `- 当前色卡：${palette} -`,
    unnamedPalette: '未命名色卡'
  },
  canvasHighlight: {
    title: '颜色高亮',
    closeAria: '关闭颜色高亮窗口',
    selectAll: '全选',
    deselectAll: '全不选',
    searchPlaceholder: '搜索颜色代码...',
    loading: '正在加载颜色...',
    replaceLabel: '将高亮颜色替换为',
    replacePlaceholder: '请选择目标颜色',
    applyReplace: '一键替换',
    empty: '没有符合条件的颜色',
    messages: {
      chooseTarget: '请选择要替换到的目标颜色。',
      chooseSource: '请先选择需要替换的高亮颜色。',
      missingTarget: '当前色卡中不存在该颜色。',
      noPixels: '未找到需要替换的像素。',
      replaced: (count, code) => `已将 ${count} 个像素替换为 ${code}。`
    }
  },
  exportWindow: {
    title: '导出设置',
    closeAria: '关闭导出设置',
    previewTitle: '预览',
    previewHint: '(滚轮缩放 · 拖拽移动 · 双击重置)',
    fileSettings: '文件设置',
    fileNameLabel: '文件名',
    fileNamePlaceholder: '输入文件名',
    fileNameSuffix: '-{width}x{height}.{ext}',
    optionsHeading: '导出选项',
    formats: {
      png: 'PNG 格式',
      jpeg: 'JPEG 格式',
      pdf: 'PDF 格式',
      pd: 'PD 工程文件'
    },
    displayHeading: '显示选项',
    displayOptions: {
      codesInclude: '包含色号',
      codesExclude: '不包含色号',
      axesInclude: '包含坐标系',
      axesExclude: '不包含坐标系'
    },
    backgroundHeading: '背景设置',
    backgroundLabel: '背景颜色',
    backgroundOptions: {
      solid: '纯色背景',
      transparent: '透明背景'
    },
    highlightHeading: '颜色高亮',
    selectAll: '全选',
    deselectAll: '全不选',
    searchPlaceholder: '搜索颜色代码...',
    loading: '正在加载颜色...',
    exportAll: '导出所有颜色高亮图',
    cancel: '取消',
    confirm: '确认导出',
    exporting: '导出中...',
    noCanvas: '请先创建画布'
  },
  preview: {
    loading: '生成预览中...'
  },
  exporter: {
    heading: '绘制图',
    total: (count) => `总数量: ${count}`,
    sectionTitle: '使用色号',
    empty: '尚未绘制任何颜色',
    paletteLabel: (label) => `- 调色板: ${label} -`,
    noCanvasAlert: '请先新建画布',
    pdfErrorConsole: 'PDF导出失败:',
    pdfErrorMessage: (message) => `PDF导出失败: ${message}`
  },
  paletteSwitch: {
    title: '切换色卡',
    closeAria: '关闭色卡切换提示',
    summary: '切换色卡会影响当前画布的颜色，请选择处理方式。',
    targetLabel: '目标色卡：',
    fallbackName: '未命名',
    buttons: {
      cancel: '取消',
      convert: '转换颜色',
      reset: '新建画布'
    }
  },
  pd: {
    exportWithoutCanvas: '请先创建画布后再导出。',
    invalidFile: 'PD 文件内容无效或已损坏。',
    canvasSizeExceeded: 'PD 文件中的画布尺寸超出限制。',
    importOverwriteConfirm: '导入 PD 文件会覆盖当前画布内容，是否继续？',
    importComplete: 'PD 文件导入完成。',
    importFailed: '无法导入 PD 文件，请确认文件格式正确。',
    paletteEmpty: 'PD 文件中的色卡为空，无法导入。',
    customPaletteLabel: '自定义色卡',
    defaultPaletteLabel: '默认色卡',
    missingCodes: (codes) => `部分色号在当前色卡中缺失，已自动忽略：${codes}`
  },
  reference: {
    title: '参考图',
    empty: '尚未添加参考图。',
    setAsBase: '作为底图',
    delete: '删除',
    confirmDelete: '确定删除这张参考图吗？',
    confirmReplaceBase: '当前已有底图，是否替换？',
    defaultName: (id) => `参考图 ${id}`,
    imageLoadFailed: '图片加载失败，请检查图片格式',
    console: {
      baseModuleFallback: '底图模块导入失败，将使用备用方案:',
      callBaseError: '调用底图函数时出错:',
      imageLoadFailed: '图片加载失败:'
    }
  },
  docs: {
    title: '说明书',
    closeAria: '关闭说明书',
    content: [
      '<h1>拼豆像素画工具说明书</h1>',
      '<h2>🧑‍🎨 作者信息</h2>',
      '<p>由 <strong>闷香红烧鱼</strong> 制作。</p>',
      '<ul>',
      '<li>Bilibili：<a href="https://space.bilibili.com/609170202" target="_blank" rel="noopener">闷香红烧鱼</a></li>',
      '<li>小红书：<a href="https://www.xiaohongshu.com/user/profile/65f420e30000000005008498" target="_blank" rel="noopener">闷香红烧鱼</a></li>',
      '</ul>',
      '<p>本网页完全免费使用，希望能方便大家进行拼豆手工草图创作( •̀ ω •́ )✧</p>',
      '<p>可以收藏下来方便以后使用！</p>',
      '<p>目前适用于电脑端，移动端会在未来做响应式<br>&#96;(*>﹏<*)′ </p>',
      '<hr>',
      '<h2>🪄 基础使用</h2>',
      '<ol>',
      '<li>创建画布。</li>',
      '<li>从色卡中选择颜色进行上色。</li>',
      '<li>完成后导出图片即可保存作品。</li>',
      '</ol>',
      '<hr>',
      '<h2>🖼 画布操作</h2>',
      '<ul>',
      '<li><strong>左键</strong>：绘制像素(铅笔和油漆桶操作相同)。</li>',
      '<li><strong>右键</strong>：擦除像素(铅笔和油漆桶操作相同)。</li>',
      '<li><strong>滚轮滚动</strong>：放大 / 缩小画布。</li>',
      '<li><strong>长按滚轮</strong>：拖动画布。</li>',
      '<li><strong>双击滚轮</strong>：重置画布视图。</li>',
      '</ul>',
      '<hr>',
      '<h2>🖱️ 吸管模式说明</h2>',
      '<ul>',
      '<li>在吸管工具模式下，<strong>左键点击</strong> 可从画布中选取像素颜色，用于当前绘图颜色。</li>',
      '</ul>',
      '<hr>',
      '<h2>🧩 底图与模板</h2>',
      '<ul>',
      '<li><strong>底图</strong>：会显示在画布底下，用于参考描绘。</li>',
      '<li><strong>模板图</strong>：会显示在独立的参考窗口中，可自由拖动和缩放。</li>',
      '</ul>',
      '<hr>',
      '<h2>🔧 底图操作</h2>',
      '<ol>',
      '<li>点击「<strong>编辑底图</strong>」按钮进入底图编辑模式。</li>',
      '<li>在该模式下：<ul>',
      '<li><strong>长按左键</strong> 可拖动底图位置。</li>',
      '<li><strong>滚轮滚动</strong> 可缩放底图比例。</li>',
      '</ul>',
      '</li>',
      '</ol>',
      '<hr>',
      '<h2>🧱 框选工具操作</h2>',
      '<ul>',
      '<li><strong>长按左键</strong> 拖动以添加选区</li>',
      '<li><strong>双击左键</strong> 翻转当前选区</li>',
      '<li><strong>长按中键</strong> 拖动选区内容</li>',
      '<li><strong>长按右键</strong> 拖动以删除选区</li>',
      '<li><strong>双击右键</strong> 清除所有选区</li>',
      '</ul>',
      '<hr>',
      '<h2>📁 导入与导出</h2>',
      '<ul>',
      '<li><strong>导出格式：</strong>',
      '<ul>',
      '<li>图片：支持 <strong>PNG</strong>、<strong>JPEG (JPG)</strong>、<strong>PDF</strong></li>',
      '<li>工程文件：<strong>.pd</strong> 格式，可在浏览器中导入继续编辑或分享。</li>',
      '</ul>',
      '</li>',
      '<li><strong>导出时可自定义：</strong>',
      '<ul>',
      '<li>背景颜色（透明或指定颜色）</li>',
      '<li>是否显示色号提示</li>',
      '<li>是否显示坐标信息</li>',
      '<li>自定义文件名</li>',
      '</ul>',
      '</li>',
      '<li><strong>导入格式：</strong>',
      '<ul>',
      '<li>支持导入 <code>.pd</code></li>',
      '</ul>',
      '</li>',
      '</ul>',
      '<hr>',
      '<h2>🎨 色卡</h2>',
      '<ul>',
      '<li>内置了常用的拼豆色卡。</li>',
      '<li>也可以手动导入自定义色卡 JSON 文件，格式如下：</li>',
      '</ul>',
      '<pre>文件名：色卡名.json\n\n文件内容：\n{\n"A1": "RGB(2, 5, 7)",\n"A2": "RGB(10, 20, 255)",\n"颜色编号": "RGB(R, G, B)",\n...\n}</pre>',
      '<p>键为颜色编号，值为 RGB 颜色值。</p>',
      '<hr>',
      '<h2>⌨️ 快捷键一览</h2>',
      '<ul>',
      '<li><strong>1</strong>：切换为铅笔工具</li>',
      '<li><strong>2</strong>：切换为油漆桶工具</li>',
      '<li><strong>3</strong>：切换为吸管工具</li>',
      '<li><strong>4</strong>：切换为框选工具</li>',
      '<li><strong>A</strong>：开启 / 关闭全屏模式</li>',
      '<li><strong>S</strong>：快速保存 PNG（无色号提示 / 无坐标）</li>',
      '<li><strong>C</strong>：打开 / 关闭参考图选框</li>',
      '<li><strong>Q</strong>：切换底图编辑模式</li>',
      '<li><strong>Z</strong>：撤回操作</li>',
      '<li><strong>X</strong>：回退操作</li>',
      '</ul>',
      '<hr>',
      '<h2>🪲 Bug 与反馈</h2>',
      '<p>如遇问题或功能建议，可在以下平台私信反馈：</p>',
      '<ul>',
      '<li>Bilibili：<a href="https://space.bilibili.com/609170202" target="_blank" rel="noopener">闷香红烧鱼</a></li>',
      '<li>小红书：<a href="https://www.xiaohongshu.com/user/profile/65f420e30000000005008498" target="_blank" rel="noopener">闷香红烧鱼</a></li>',
      '</ul>',
      '<p>若出现严重 Bug，将及时修复并更新版本。</p>'
    ].join('\n')
  },
  update: {
    title: '更新说明',
    closeAria: '关闭更新说明',
    content: [
      '<h1>更新说明</h1>',
      '<p class="time">更新时间：2025.11.3</p>',
      '<h2>🚀 更新日志 v1.5</h2>',
      '<h3>⚙️ 新增功能</h3>',
      '<ul>',
      '<li><strong>底图系统全面升级</strong>：支持 <strong>数值无极缩放（1% - 200%）</strong>，无论微调还是整体预览，都能精准掌控。</li>',
      '<li><strong>画布结构重构</strong>：可直接 <strong>扩大与裁剪</strong>，在不丢失任何像素的前提下自由调整尺寸。</li>',
      '<li><strong>色彩系统增强</strong>：',
      '<ul>',
      '<li>新增 <strong>颜色高亮显示</strong> 与 <strong>导出</strong> 功能，让关键色一目了然。</li>',
      '<li>支持 <strong>一键替换指定颜色</strong>，大规模调色从此不再繁琐。</li>',
      '<li>切换 <strong>色卡</strong> 时可使用 <strong>智能颜色映射</strong>，自动匹配相似色号，无需重建画布。</li>',
      '</ul>',
      '</li>',
      '<li><strong>像素比例自定义</strong>：可自由设置 <strong>1:x</strong> 精度比例，兼顾细节表现与效率输出。</li>',
      '<li><strong>工程文件全面优化</strong>：<code>.pd</code> 文件结构更新，数据存储更精确，导入后可完美还原画布状态与配置。</li>',
      '<li><strong>代码性能全面优化</strong>：核心逻辑压缩与渲染路径重构，<strong>长时间使用也能保持流畅不卡顿</strong>。</li>',
      '</ul>',
      '<hr>',
      '<h2>🐛 稳定性修复</h2>',
      '<ul>',
      '<li>修复 <strong>显示色号</strong> 与 <strong>画布透明度</strong> 无法实时生效的问题。</li>',
      '<li>修复 <strong>多次点击色号</strong> 导致网页卡死的情况。</li>',
      '<li>修复 <strong>.pd 工程文件</strong> 在部分环境下无法导入的问题。</li>',
      '</ul>',
      '<hr>',
      '<h2>🧩 使用体验升级</h2>',
      '<ul>',
      '<li>新增 <strong>退出前提醒</strong> 机制，当画布存在绘制内容时自动提示，防止误关闭造成作品丢失。</li>',
      '</ul>'
    ].join('\n')
  },
  console: {
    imageOperations: {
      flipHorizontal: '无法执行水平翻转：画布未创建',
      flipVertical: '无法执行垂直翻转：画布未创建',
      rotate: '无法执行旋转：画布未创建'
    },
    paletteFallback: '自动发现默认色卡失败，正在使用兼容列表。'
  }
};
